### ISSUE TITLE
Use SIL's Fallback Font

### ISSUE THREAD

**Issue by davelab6** [impallari/Font-Testing-Page#28]
A user told me, 

> I loaded my font into www.impallari.com/testing/, but unfortunately it was very difficult to view in isolation as the “default” font was still representing the missing glyphs that I have not worked on yet.

Using a non-system fallback font, like http://scripts.sil.org/UnicodeBMPFallbackFont

**Comment by impallari** [comment]
Closed here, but continues in https://github.com/impallari/Font-Testing-Page/issues/41
