### ISSUE TITLE
On Deva Syllables page, move 'impossible' combinations to their own row

### ISSUE THREAD

**Issue by davelab6** [impallari/Font-Testing-Page#37]
As per https://github.com/girish-dalvi/Ek-Mukta/issues/12, on Deva Syllables page, move 'impossible' combinations to their own row

**Comment by davelab6** [comment]
It would be nice to have the conjuncts in a table that explains more about them

http://en.wikibooks.org/wiki/Hindi/Consonant_combinations

http://www.garretwilson.com/education/languages/hindi/devanagari/lesson4/conjuncts.xhtml

**Comment by impallari** [comment]
As Girish said, It's very difficult to separate the impossible combinations.
Only can do it if someone provides the list.
Closing this and opening a new issue for the conjuncts chart.
