### ISSUE TITLE
Highlight missing glyphs

### ISSUE THREAD

**Issue by larsenwork** [impallari/Font-Testing-Page#41]
On the "Latin" and "World Scipts" pages. 

So that the missing characters get greyed out or become red or bold or

Don't know how to code this though.

I know you can use javascript ([jsfiddle](http://jsfiddle.net/ZzBN9/15/)) or the unicode range in [@font-face](https://developer.mozilla.org/en-US/docs/Web/CSS/unicode-range) for styling but I'm not sure how to detect the missing glyphs.

**Comment by weiweihuanghuang** [comment]
Related: https://github.com/impallari/Font-Testing-Page/issues/28

**Comment by davelab6** [comment]
2 ways, either a fallback font like sil uni code or adobe blank, or
opentype.js to get the cmap data for use by lettering.js to do the coloring
