### ISSUE TITLE
[fontdrag.js] add "woff2" to acceptedFileExtensions?

### ISSUE THREAD

**Issue by anthrotype** [impallari/Font-Testing-Page#44]
Hello,

Now that both Chrome and Firefox (v35, via about:config) support woff2, it would be nice to be able to add support for the new format to the Font Testing Page.

For the time being, I simply rename the font file extension to, say, ".woff", and the WOFF2 is loaded correctly by supported browsers.

So I guess it's just a matter of adding the "woff2" extension to the fontdrag.js list of acceptedFileExtension...
(but maybe this feature request could also be forwarded to @ryanseddon's font-dragr repository)

Thanks a lot,

Cosimo

**Comment by impallari** [comment]
Done
