### ISSUE TITLE
Create layout page that shows multiple fonts together for family comparison

### ISSUE THREAD

**Issue by weiweihuanghuang** [impallari/Font-Testing-Page#47]
This is an important feature that's missing as font weights are often used together and possibly on the same line, it's necessary to proof webfonts in a family together.

**Comment by davelab6** [comment]
I discussed this with @impallari about a year ago and at that time he
wanted to keep this tool per font not per family so I started
Github.com/metapolator/ddt which yoy can try at testmyfont.com/demo

**Comment by weiweihuanghuang** [comment]
@davelab6 Wow nice! The typographic adjustment (font size, leading etc) is really needed, I've been slowly trying to add these features into the Impallari version!

**Comment by impallari** [comment]
Just use Google Chrome: Drop a few font, copy some text using one font, change to other font and paste the text... and voila!

**Comment by davelab6** [comment]
I suggest to reopen this and rename it as 'Add a help tab, with help text
and tips and tricks on how to use the tool'
