### ISSUE TITLE
Request for Tamil

### ISSUE THREAD

**Issue by VanillaandCream** [impallari/Font-Testing-Page#51]
Hi Pablo,

Please can you integrate Tamil testing. I am looking at the world scripts where there is Tamil, however a more elaborate testing interface will be very useful.

Thanks in advance.

Best,
Pria

**Comment by enathu** [comment]
@VanillaandCream I have forked this and made Tamil font testing page, last year. 
You can see it here: https://github.com/enathu/tamil-font-testing-page 
Live here: http://niram.org/tamil-font-test 

Hope that helps.

**Comment by VanillaandCream** [comment]
Thanks, this is very helpful. Great work too.
