### ISSUE TITLE
Norvig's Ngrams

### ISSUE THREAD

**Issue by davelab6** [impallari/Font-Testing-Page#67]
Include ngrams from http://norvig.com/mayzner.html :)

**Comment by impallari** [comment]
Done

**Comment by davelab6** [comment]
AWESOME :D

On 6 May 2016 at 03:45, Pablo Impallari <notifications@github.com> wrote:

> Closed #67 <https://github.com/impallari/Font-Testing-Page/issues/67>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/impallari/Font-Testing-Page/issues/67#event-652347503>
>



-- 
Cheers
Dave

**Comment by impallari** [comment]
Also added a new page, having the most popular words in the Google Books corpus
