### ISSUE TITLE
Forbidden 403

### ISSUE THREAD

**Issue by pathumego** [impallari/Font-Testing-Page#68]
<img width="614" alt="screen shot 2016-01-20 at 11 29 14 pm" src="https://cloud.githubusercontent.com/assets/6846609/12466612/b48a859e-bfcd-11e5-9461-cfebb4e45def.png">

**Comment by davelab6** [comment]
I confirm this.

You can clone this repo and inside it run `$ php -S 127.0.0.1:8080` then
visit http://127.0.0.1:8080 to use the page while its down

**Comment by davelab6** [comment]
I made https://github.com/impallari/Font-Testing-Page/pull/69 to explain this in the README

**Comment by impallari** [comment]
Hosting is down, it's supposed to be back online tomorrow or so...

2016-01-20 20:42 GMT-03:00 Dave Crossland <notifications@github.com>:

> I made #69 <https://github.com/impallari/Font-Testing-Page/pull/69> to
> explain this in the README
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/impallari/Font-Testing-Page/issues/68#issuecomment-173404050>
> .
>



-- 
Un Abrazo
Pablo Impallari
