### ISSUE TITLE
Letter frequencies for many languages

### ISSUE THREAD

**Issue by davelab6** [impallari/Font-Testing-Page#74]
FYI http://simia.net/letters/ has letter frequencies for many languages

**Comment by impallari** [comment]
Thanks.

**Comment by moyogo** [comment]
Which commit fixed this?

**Comment by davelab6** [comment]
Pablo closes issues which he has no intention of taking action on.

**Comment by moyogo** [comment]
OK. Thanks for clarifying that.

**Comment by impallari** [comment]
Just to clarify:
I don't see how this simple bit of data can be translated into a useful content tab for the testing page.
If anyone has an idea for it, I'm open to suggestions
