### ISSUE TITLE
'numr' and 'dnom' feature tags

### ISSUE THREAD

**Issue by StevanWhite** [impallari/Font-Testing-Page#86]
The 'numr' and 'dnom' features aren't supposed to be activated at the application level.
Instead they are used only by the 'frac' lookup.

https://www.microsoft.com/typography/otspec/features_ko.htm#numr
"UI suggestion: This feature should normally be called by an application when the user applies the frac feature."

**Comment by impallari** [comment]
You are right. 
However, since this is a Testing app, it still good to have them at hand for the purpose of testing.

**Comment by StevanWhite** [comment]
Hi,

Well, it's a strange sort of test of a feature.
I think that, if activating 'numr' or 'dnom' changes something in the display, they are configured incorrectly, and won't work properly with 'frac'.

In which tests do these switches make a difference?
