### ISSUE TITLE
Also support standard file picker instead of only drag and drop

### ISSUE THREAD

**Issue by Hexstream** [impallari/Font-Testing-Page#93]
This tool only supports drag & drop, which is not convenient for everyone.

It would be great if the standard file picker dialog was also supported.

----------

PS: Thank you for Kaushan Script! I use it for page headings across [all my websites](https://abc.hexstream.xyz/websites/). :)

**Comment by Hexstream** [comment]
I see this has been closed as "completed", but I can't find the feature on [the site](https://www.impallari.com/testing/).

Has this been or will this be implemented or not?

Drag & Drop is ultra painful with my tiling window manager.
I usually have one maximized window per workspace.

**Comment by impallari** [comment]
No

**Comment by Hexstream** [comment]
Charming.

**Comment by impallari** [comment]
The ugly part of being a in charge of project is having to say no to some requests that I don't consider necessary... people get disappointed... shit happens, c'est la vie... 

If you need it so badly, at least you have the source code available to you. You can fork it and add it to your local version. Thats the best I can offer you at this point. Sorry to disappoint you.

**Comment by Hexstream** [comment]
See, this is what an appropriate response looks like. It's not that hard!
